### ISSUE TITLE
Indexing of Expenses

### ISSUE THREAD

**Issue by adam110th** [LucisVivae/Australian-Fire-Calculator-excel#2]
Hi there,

Thanks for releasing this spreadsheet. I've just downloaded and have been reviewing it - looking at the calculations, it looks you aren't increasing your expenses by the inflation rate - is there a reason for this?

**Comment by LucisVivae** [comment]
Everything is in real dollars and inflation is used to calculate the adjusted growth rate to take into account the time value of money. This ensures that the nominal value of expenses is the same as the real value even though the nominal value will be higher.
